name: Build Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest  # or ubuntu-latest, depending on your target OS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # or your desired version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create Executable
      run: pyinstaller --onefile your_script_name.py

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: ./dist/your_script_name.exe
